### PR TITLE
tun_index function to expose interface index

### LINKED ISSUE #110: Getting the network interface index for a device
Currently, I use this crate by creating the interface, and looking up the interface by name and getting the ID so that I can use it in creating routes and other things. However, this is almost flaky in practice because of the way names are handled on different platforms and I would rather get the ID directly if that is possible. Or, are the low level details such that I should just search through the interface list and it would be just as efficient?

### PR DESCRIPTION
**Pull request by emanuele-em**
- [x] Expose interface id on Linux
- [x] Add interface id to examples
- [x] close #110

### CODE REVIEW

**Comment by ssrlive** [comment]
Thank you! But can you confirm that your implementation of freebsd is correct? Because I don't have a freebsd test environment.

**Comment by emanuele-em** [comment]
@ssrlive no idea actually, I thought it was the same as macOS but it was only (likely wrong) assumption.

**Comment by emanuele-em** [comment]
@ssrlive for now I replace that part of code with `Err(...)`, maybe it's better

**Comment by ssrlive** [comment]
I have make some changes, please test it on linux and macos. 
if it's fine, i'll merge it.

**Comment by emanuele-em** [comment]
@ssrlive tested both on linux and macos, it works correctly -> ready to merge :)

**Pull request merged**
